name: Terraform AWS Infrastructure with OIDC

on:
  push:
    branches:
      - main  # Trigger workflow on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch
  workflow_dispatch:  # This allows manual triggers
    inputs:
      action:
        description: 'Action to perform: apply or destroy'
        required: true
        default: 'apply'  # Default action is 'apply'
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify the Terraform version here

      # Authenticate with AWS using OIDC
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::418272776375:role/oidc-actions  # Ensure this ARN is correct
          aws-region: ap-northeast-3  # Your AWS region
          role-session-name: samplerolesession

      # # Initialize Terraform
      # - name: Terraform Init
      #   run: terraform init

      # # Terraform Plan (to preview the changes)
      # - name: Terraform Plan
      #   run: terraform plan

      # # Conditionally apply or destroy based on the action input
      # - name: Terraform Apply
      #   if: ${{ github.event.inputs.action == 'apply' }}  # Apply if the action is 'apply'
      #   run: terraform apply -auto-approve

      # # Conditionally destroy based on the action input
      # - name: Terraform Destroy
      #   if: ${{ github.event.inputs.action == 'destroy' }}  # Destroy if the action is 'destroy'
      #   run: terraform destroy -auto-approve
